Add Certificate validation (#60)
This commit adds options to the client regarding how to validate
TLS certificates when establishing a HTTPS connection. It is common
to use self-signed certificates, which the user may want to validate accordingly:

1. Default - the default underlying validation
2. Full validation - issued by a trusted authority (CA) and hostname verification
3. Certificate validation - issued by a trusted authority (CA)
4. None - no validation. Not recommended for production but useful for development.

Within the certificate validation integration tests, 
make different assertions based on the platform OS on which
the tests are running.

With reqwest's native-tls, it seems there is a difference in what
certificates are supported when configuring validation with self-signed certificates
signed by your own CA.

On Windows, validation can be configured using either the certificate or the CA
used to generate the certificate, when running in Full or Certificate modes.

On Linux however, Full and Certificate validation can be configured only with the CA used to
generate the certificate. Attempting to use the certificate itself fails with

```
Error: Error { kind: Http(reqwest::Error { kind: Request, url: "https://es1:9200/", source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "../ssl/statem/statem_clnt.c", line: 1915 }]))) }, X509VerifyResult { code: 20, error: "unable to get local issuer certificate" })) }) }
```

This _seems_ incorrect because it should be valid to anchor trust on an
intermediate certificate. For now though, validation with a 
self-signed certificate signed by own CA works on both Windows and Linux 
when the client is configured with the CA cert, which is sufficient.

Closes #55