Handle certification validation assertions across platforms
This commit updates the certificate validation integration tests
to make different assertions based on the platform OS on which
the tests are running.

With reqwest's native-tls, it seems there is a difference in what
certificates are supported when configuring validation with self-signed certificates.

On Windows, validation can be configured using either the certificate or the CA
used to generate the certificate when running in Full or Certificate modes.

On Linux however, Full and Certificate validation can be configured only with the CA used to
generate the certificate. Attempting to use the certificate itself fails with

```
Error: Error { kind: Http(reqwest::Error { kind: Request, url: "https://es1:9200/", source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "../ssl/statem/statem_clnt.c", line: 1915 }]))) }, X509VerifyResult { code: 20, error: "unable to get local issuer certificate" })) }) }
```

This seems incorrect because it should be valid to anchor trust on an
intermediate certificate.